function calibration=createTestImuCalibration(synthetic)
if nargin<1, synthetic=true; end
config=getImuConfig();
quality=struct('valid',true,'score',1,'gravityMagnitude',9.81, ...
    'gravityDirectionStdDeg',0,'forwardCoherence',1,'forwardAccelerationMean',1, ...
    'forwardAccelerationStd',0,'orthogonalityError',0,'determinant',1, ...
    'stationarySampleCount',100,'forwardSampleCount',100);
metadata=struct('busId',config.busId,'imuUid',config.uid,'deviceIdentifier',18, ...
    'firmwareVersion',[2 0 15],'sensorFusionMode',config.sensorFusionMode, ...
    'sampleRateHz',config.sampleRateHz,'algorithmVersion',"test", ...
    'synthetic',logical(synthetic));
calibration=struct('version',2,'createdAt',datetime('now','TimeZone','UTC'), ...
    'axisConvention','X forward, Y left, Z up','rotationVehicleFromSensor',eye(3), ...
    'bias',struct('linearAccelerationSensor',zeros(3,1), ...
    'angularVelocitySensor',zeros(3,1)), ...
    'sensorAxes',struct('forward',[1;0;0],'left',[0;1;0],'up',[0;0;1]), ...
    'quality',quality,'configuration',struct(),'metadata',metadata);
end
