projectRoot = fileparts(fileparts(mfilename('fullpath')));
run(fullfile(projectRoot, 'startup.m'));

config = getImuConfig();

imu = ImuBrick2( ...
    config.uid, ...
    config.host, ...
    config.port);

cleanup = onCleanup(@()imu.disconnect());

report = diagnoseImuBrick2UsingExistingConnection(imu);
if ~report.success
    error("IMU:PreflightFailed", ...
        "Калибровка запрещена: аппаратная диагностика не пройдена.");
end

calibration = runImuInstallationCalibration( ...
    imu, ...
    config.busId, ...
    config.calibrationDirectory, ...
    report);

clear projectRoot;
