projectRoot=fileparts(fileparts(mfilename('fullpath')));
run(fullfile(projectRoot,"startup.m"));
assertImuRuntimeReady();
imuConfig=getImuConfig();
calibrationFile=resolveProjectPath(fullfile(imuConfig.calibrationDirectory, ...
    imuConfig.busId+"_imu_mount.mat"));
calibration=loadImuCalibration(calibrationFile,imuConfig.busId,imuConfig.uid);
imu=ImuBrick2(imuConfig.uid,imuConfig.host,imuConfig.port);
imuCleanup=onCleanup(@()imu.disconnect());
preflight=diagnoseImuBrick2UsingExistingConnection(imu);
disp(preflight);
assert(preflight.success,"IMU:PreflightFailed","Full hardware preflight failed.");

options=getRealtimeDrivingConfig();
options.enableLivePlot=false; options.enableRecording=false; options.UseTimer=true;
monitor=RealtimeDrivingMonitor(imu,calibration,options);
monitorCleanup=onCleanup(@()delete(monitor));
monitor.start(); pause(120); runningAtEnd=monitor.IsRunning; summary=monitor.stop();

[gitStatus,commit]=system('git rev-parse HEAD');
if gitStatus~=0, commit="unknown"; else, commit=strtrim(string(commit)); end
report=struct('commit',commit,'matlabVersion',string(version), ...
    'javaVersion',string(version('-java')),'uid',string(preflight.uid), ...
    'firmwareVersion',preflight.firmwareVersion, ...
    'sensorFusionMode',preflight.sensorFusionMode, ...
    'durationSeconds',summary.durationSeconds, ...
    'acquisitionDurationSeconds',summary.acquisitionDurationSeconds, ...
    'shutdownDurationSeconds',summary.shutdownDurationSeconds, ...
    'samplesProcessed',summary.samplesProcessed, ...
    'averageFrequencyHz',summary.averageFrequencyHz, ...
    'missingSamples',summary.missingSamples, ...
    'overflowDropped',summary.overflowDropped, ...
    'staleSessionDropped',summary.staleSessionDropped, ...
    'invalidSamples',summary.invalidSamples, ...
    'maximumCallbackAgeMs',summary.maximumCallbackAgeMs, ...
    'tailSamplesDrained',summary.tailSamplesDrained, ...
    'stopDrainDurationSeconds',summary.stopDrainDurationSeconds, ...
    'stopDrainPollIntervalSeconds',options.stopDrainPollIntervalSeconds, ...
    'stopDrainTimedOut',summary.stopDrainTimedOut, ...
    'finalCallbackStats',summary.finalCallbackStats, ...
    'monitorRunningAtEnd',runningAtEnd,'summarySuccess',summary.success, ...
    'errors',summary.errors,'warnings',summary.warnings);
report.success=preflight.success && runningAtEnd && summary.success && ...
    ~summary.stopDrainTimedOut && summary.shutdownDurationSeconds>=0 && ...
    summary.tailSamplesDrained>=0 && ...
    summary.invalidSamples==0 && isempty(summary.lastError) && ...
    summary.overflowDropped==0 && summary.staleSessionDropped==0 && ...
    summary.missingSamples==0 && summary.acquisitionDurationSeconds>0 && ...
    summary.samplesProcessed/summary.acquisitionDurationSeconds>=40 && ...
    summary.samplesProcessed/summary.acquisitionDurationSeconds<=60 && ...
    summary.maximumCallbackAgeMs<=options.maximumSampleAgeMs;

artifactDirectory=resolveProjectPath('artifacts');
if ~isfolder(artifactDirectory), mkdir(artifactDirectory); end
stamp=char(datetime('now','Format','yyyyMMdd_HHmmss'));
matFile=fullfile(artifactDirectory,['realtime_acceptance_',stamp,'.mat']);
jsonFile=fullfile(artifactDirectory,['realtime_acceptance_',stamp,'.json']);
save(matFile,'report','preflight','summary','-v7');
fileId=fopen(jsonFile,'w'); assert(fileId>=0);
fileCleanup=onCleanup(@()fclose(fileId));
fprintf(fileId,'%s',jsonencode(report,'PrettyPrint',true)); clear fileCleanup;
report.matFile=string(matFile); report.jsonFile=string(jsonFile); disp(report);
assert(report.success,"IMU:RealtimeAcceptanceFailed","Real-time hardware acceptance failed.");
clear projectRoot;
