projectRoot = fileparts(fileparts(mfilename('fullpath')));
run(fullfile(projectRoot, "startup.m"));
assertImuRuntimeReady();
imuConfig = getImuConfig();
calibrationFile = resolveProjectPath(fullfile( ...
    imuConfig.calibrationDirectory, imuConfig.busId + "_imu_mount.mat"));
calibration = loadImuCalibration(calibrationFile, imuConfig.busId, imuConfig.uid);
imu = ImuBrick2(imuConfig.uid, imuConfig.host, imuConfig.port);
imuCleanup = onCleanup(@()imu.disconnect());
preflight = diagnoseImuBrick2UsingExistingConnection(imu);
disp(preflight); assert(preflight.success);
options = getRealtimeDrivingConfig();
options.enableLivePlot = true; options.enableRecording = true;
monitor = RealtimeDrivingMonitor(imu, calibration, options);
monitorCleanup = onCleanup(@()delete(monitor));
monitor.OnEventCompleted = @(~,event)printRealtimeDrivingEvent(event);
monitor.start();
disp("Real-time monitor запущен.");
disp("Для остановки выполните: summary = monitor.stop();");
clear projectRoot;
