function diagnostics = assertImuAcceptanceClassApi(options)
%ASSERTIMUACCEPTANCECLASSAPI Detect stale loaded handle-class definitions.
if nargin < 1 || isempty(options), options = struct(); end
if ~isfield(options,'MethodListFunction')
    options.MethodListFunction = @(name)string(methods(char(name)));
end
if ~isfield(options,'WhichFunction')
    options.WhichFunction = @(name)string(which(char(name)));
end
if ~isfield(options,'ThrowOnFailure'), options.ThrowOnFailure = true; end

specifications = { ...
    'ImuBrick2', ["claimStreamOwner","releaseStreamOwner","quiesce", ...
        "clearCallbackBuffer","drainCallbackSamples","getCallbackStats"]; ...
    'ImuInstallationCalibrationController', ["runBlocking","cancel", ...
        "close","getStatus"]; ...
    'RealtimeDrivingMonitor', ["start","stop","getStats"]};
valid = false(1,3); sources = strings(1,3); missing = cell(1,3);
for index = 1:3
    className = specifications{index,1}; required = specifications{index,2};
    available = string(options.MethodListFunction(className));
    missing{index} = required(~ismember(required,available));
    valid(index) = isempty(missing{index});
    sources(index) = string(options.WhichFunction(className));
end
diagnostics = struct('imuBrick2Source',sources(1), ...
    'controllerSource',sources(2),'monitorSource',sources(3), ...
    'imuBrick2MethodsValid',valid(1),'controllerMethodsValid',valid(2), ...
    'monitorMethodsValid',valid(3),'matlabRestartRequired',~all(valid), ...
    'missingImuBrick2Methods',missing{1}, ...
    'missingControllerMethods',missing{2},'missingMonitorMethods',missing{3});
if options.ThrowOnFailure && ~all(valid)
    error('IMU:StaleMatlabClassDefinition', '%s\n%s\n%s', ...
        'MATLAB has an older class definition loaded.', ...
        'Close IMU objects and restart MATLAB.', ...
        'Verify the checkout commit before retrying.');
end
end
