function config=getBusDrivingSystemDashboardConfig()
%GETBUSDRIVINGSYSTEMDASHBOARDCONFIG Bounded unified-dashboard settings.
config=struct('refreshHz',5,'maximumRefreshHz',10, ...
    'signalHistorySeconds',30,'maximumEventRows',500, ...
    'maximumLogRows',1000,'maximumStageHistory',100, ...
    'showRawSignals',true,'showFilteredSignals',true, ...
    'showThresholds',true,'showEventMarkers',true, ...
    'enableCalibrationTab',true,'enableRecordingTab',true, ...
    'enableAcceptanceTab',true,'autoScaleSignals',false, ...
    'maximumRenderMilliseconds',50,'closeStopsSystem',true);
config=validateBusDrivingSystemDashboardConfig(config);
end
