function report = runRealtimeHardwareAcceptance()
%RUNREALTIMEHARDWAREACCEPTANCE Exercise the production monitor lifecycle.
assertImuAcceptanceClassApi();
checkoutCommit=getImuAcceptanceCommit();
assertImuRuntimeReady();
imuConfig=getImuConfig();
calibrationFile=resolveProjectPath(fullfile(imuConfig.calibrationDirectory, ...
    imuConfig.busId+"_imu_mount.mat"));
calibration=loadImuCalibration(calibrationFile,imuConfig.busId,imuConfig.uid);
imu=ImuBrick2(imuConfig.uid,imuConfig.host,imuConfig.port);
imuCleanup=onCleanup(@()imu.disconnect());
preflight=diagnoseImuBrick2UsingExistingConnection(imu);
if ~preflight.success
    error('IMU:PreflightFailed','%s',strjoin(preflight.errors," "));
end
options=getRealtimeDrivingConfig();
options.enableLivePlot=false; options.enableRecording=false; options.UseTimer=true;
monitor=RealtimeDrivingMonitor(imu,calibration,options);
monitorCleanup=onCleanup(@()delete(monitor));
monitor.start(); pause(120); runningAtEnd=monitor.IsRunning; summary=monitor.stop();
report=struct('commit',checkoutCommit,'matlabVersion',string(version), ...
    'javaVersion',string(version('-java')),'uid',string(preflight.uid), ...
    'busId',imuConfig.busId,'firmwareVersion',preflight.firmwareVersion, ...
    'sensorFusionMode',preflight.sensorFusionMode, ...
    'durationSeconds',summary.durationSeconds, ...
    'acquisitionDurationSeconds',summary.acquisitionDurationSeconds, ...
    'shutdownDurationSeconds',summary.shutdownDurationSeconds, ...
    'samplesProcessed',summary.samplesProcessed, ...
    'averageFrequencyHz',summary.averageFrequencyHz, ...
    'missingSamples',summary.missingSamples,'overflowDropped',summary.overflowDropped, ...
    'staleSessionDropped',summary.staleSessionDropped, ...
    'invalidSamples',summary.invalidSamples, ...
    'maximumCallbackAgeMs',summary.maximumCallbackAgeMs, ...
    'tailSamplesDrained',summary.tailSamplesDrained, ...
    'stopDrainDurationSeconds',summary.stopDrainDurationSeconds, ...
    'stopDrainPollIntervalSeconds',options.stopDrainPollIntervalSeconds, ...
    'stopDrainTimedOut',summary.stopDrainTimedOut, ...
    'finalCallbackStats',summary.finalCallbackStats, ...
    'monitorRunningAtEnd',runningAtEnd,'summarySuccess',summary.success, ...
    'errors',summary.errors,'warnings',summary.warnings);
report.success=preflight.success && runningAtEnd && summary.success && ...
    ~summary.stopDrainTimedOut && summary.shutdownDurationSeconds>=0 && ...
    summary.tailSamplesDrained>=0 && summary.invalidSamples==0 && ...
    isempty(summary.lastError) && summary.overflowDropped==0 && ...
    summary.staleSessionDropped==0 && summary.missingSamples==0 && ...
    summary.acquisitionDurationSeconds>0 && ...
    summary.samplesProcessed/summary.acquisitionDurationSeconds>=40 && ...
    summary.samplesProcessed/summary.acquisitionDurationSeconds<=60 && ...
    summary.maximumCallbackAgeMs<=options.maximumSampleAgeMs;
report=saveRealtimeReport(report,preflight,summary);
end

function report=saveRealtimeReport(report,preflight,summary)
artifactDirectory=resolveProjectPath('artifacts');
if ~isfolder(artifactDirectory), mkdir(artifactDirectory); end
stamp=char(datetime('now','Format','yyyyMMdd_HHmmss_SSS'));
stem=fullfile(artifactDirectory,['realtime_acceptance_' stamp]);
report.matFile=string(stem)+".mat"; report.jsonFile=string(stem)+".json";
save(char(report.matFile),'report','preflight','summary','-v7');
fileId=fopen(char(report.jsonFile),'w');
if fileId<0, error('IMU:AcceptanceSaveFailed','Cannot write %s.',report.jsonFile); end
fileCleanup=onCleanup(@()fclose(fileId));
fprintf(fileId,'%s',jsonencode(report,'PrettyPrint',true));
end
