function config = validateDrivingAnalysisConfig(config)
%VALIDATEDRIVINGANALYSISCONFIG Validate offline event-analysis settings.

if ~isstruct(config) || ~isscalar(config)
    error('IMU:InvalidDrivingAnalysisConfig', ...
        'Driving analysis config must be a scalar structure.');
end
required = {'targetSampleRateHz','maximumGapSamples','segmentGapSeconds', ...
    'medianWindowSamples','outlierMadThreshold','lowPassCutoffHz', ...
    'brakingStartThreshold','brakingStopThreshold', ...
    'accelerationStartThreshold','accelerationStopThreshold', ...
    'lateralStartThreshold','lateralStopThreshold', ...
    'yawRateStartThresholdDegPerSecond','yawRateStopThresholdDegPerSecond', ...
    'verticalShockThreshold','jerkCandidateThreshold', ...
    'minimumEventDurationSeconds','maximumMergeGapSeconds', ...
    'preEventSeconds','postEventSeconds','analysisVersion'};
missing = setdiff(required, fieldnames(config));
if ~isempty(missing)
    error('IMU:InvalidDrivingAnalysisConfig', ...
        'Missing driving analysis setting: %s.', missing{1});
end
positive = {'targetSampleRateHz','segmentGapSeconds','outlierMadThreshold', ...
    'lowPassCutoffHz','accelerationStartThreshold', ...
    'accelerationStopThreshold','lateralStartThreshold', ...
    'lateralStopThreshold','yawRateStartThresholdDegPerSecond', ...
    'yawRateStopThresholdDegPerSecond','verticalShockThreshold', ...
    'jerkCandidateThreshold','minimumEventDurationSeconds', ...
    'maximumMergeGapSeconds','preEventSeconds','postEventSeconds'};
for index = 1:numel(positive)
    validateattributes(config.(positive{index}), {'numeric'}, ...
        {'scalar','real','finite','positive'}, mfilename, positive{index});
end
validateattributes(config.maximumGapSamples, {'numeric'}, ...
    {'scalar','real','finite','integer','nonnegative'});
validateattributes(config.medianWindowSamples, {'numeric'}, ...
    {'scalar','real','finite','integer','positive'});
if mod(config.medianWindowSamples, 2) ~= 1
    error('IMU:InvalidDrivingAnalysisConfig', ...
        'medianWindowSamples must be odd.');
end
if config.lowPassCutoffHz >= config.targetSampleRateHz / 2
    error('IMU:InvalidDrivingAnalysisConfig', ...
        'lowPassCutoffHz must be below Nyquist frequency.');
end
if ~(config.brakingStartThreshold < config.brakingStopThreshold && ...
        config.brakingStopThreshold < 0)
    error('IMU:InvalidDrivingAnalysisConfig', ...
        'Braking stop threshold must be weaker than the negative start threshold.');
end
if config.accelerationStopThreshold >= config.accelerationStartThreshold || ...
        config.lateralStopThreshold >= config.lateralStartThreshold || ...
        config.yawRateStopThresholdDegPerSecond >= ...
            config.yawRateStartThresholdDegPerSecond
    error('IMU:InvalidDrivingAnalysisConfig', ...
        'Each positive stop threshold must be weaker than its start threshold.');
end
if ~(ischar(config.analysisVersion) || ...
        (isstring(config.analysisVersion) && isscalar(config.analysisVersion))) || ...
        strlength(string(config.analysisVersion)) == 0
    error('IMU:InvalidDrivingAnalysisConfig', ...
        'analysisVersion must be nonempty text.');
end
end
