function config = validateRealtimeDrivingConfig(config)
%VALIDATEREALTIMEDRIVINGCONFIG Validate bounded causal monitor settings.

if ~isstruct(config) || ~isscalar(config)
    error('IMU:InvalidRealtimeConfig', 'Realtime config must be a scalar struct.');
end
required = fieldnames(getDefaultsWithoutValidation());
missing = setdiff(required, fieldnames(config));
if ~isempty(missing)
    error('IMU:InvalidRealtimeConfig', 'Missing realtime setting: %s.', missing{1});
end
positive = {'sampleRateHz','callbackPeriodMs','pollPeriodSeconds', ...
    'maximumPollSamples','lowPassCutoffHz','medianWindowSamples', ...
    'outlierMadThreshold','accelerationStartThreshold','accelerationStopThreshold', ...
    'lateralStartThreshold','lateralStopThreshold', ...
    'yawRateStartThresholdDegPerSecond','yawRateStopThresholdDegPerSecond', ...
    'verticalShockThreshold','jerkCandidateThreshold','minimumEventDurationSeconds', ...
    'maximumEventSilenceSeconds','verticalShockReleaseSamples','maximumSampleAgeMs', ...
    'historySeconds','eventHistoryLimit','maximumConsecutiveErrors','plotRefreshHz', ...
    'stopDrainTimeoutSeconds','stopDrainEmptyPasses','stopDrainPollIntervalSeconds', ...
    'maximumRecordingDurationSeconds','minimumFreeDiskBytes','maximumSessionBytes', ...
    'recordingGuardPeriodSeconds'};
for index = 1:numel(positive)
    validateattributes(config.(positive{index}), {'numeric'}, ...
        {'scalar','real','finite','positive'}, mfilename, positive{index});
end
integers = {'maximumPollSamples','medianWindowSamples','verticalShockReleaseSamples', ...
    'eventHistoryLimit','maximumConsecutiveErrors','stopDrainEmptyPasses'};
for index = 1:numel(integers)
    validateattributes(config.(integers{index}), {'numeric'}, {'integer'});
end
if config.stopDrainPollIntervalSeconds > config.stopDrainTimeoutSeconds
    error('IMU:InvalidRealtimeConfig', ...
        'stopDrainPollIntervalSeconds must not exceed stopDrainTimeoutSeconds.');
end
if mod(config.medianWindowSamples, 2) ~= 1
    error('IMU:InvalidRealtimeConfig', 'medianWindowSamples must be odd.');
end
if config.lowPassCutoffHz >= config.sampleRateHz / 2
    error('IMU:InvalidRealtimeConfig', 'lowPassCutoffHz must be below Nyquist.');
end
if ~(config.brakingStartThreshold < config.brakingStopThreshold && ...
        config.brakingStopThreshold < 0)
    error('IMU:InvalidRealtimeConfig', 'Braking hysteresis is invalid.');
end
if config.accelerationStopThreshold >= config.accelerationStartThreshold || ...
        config.lateralStopThreshold >= config.lateralStartThreshold || ...
        config.yawRateStopThresholdDegPerSecond >= ...
        config.yawRateStartThresholdDegPerSecond
    error('IMU:InvalidRealtimeConfig', 'Positive hysteresis is invalid.');
end
logicalFields = {'stopOnOverflow','stopOnSequenceGap','enableLivePlot', ...
    'enableRecording','UseTimer','DisconnectImuOnDelete','AllowSyntheticCalibration'};
for index = 1:numel(logicalFields)
    value = config.(logicalFields{index});
    if ~(islogical(value) && isscalar(value))
        error('IMU:InvalidRealtimeConfig', '%s must be logical.', logicalFields{index});
    end
end
if ~(ischar(config.recordingDirectory) || ...
        (isstring(config.recordingDirectory) && isscalar(config.recordingDirectory)))
    error('IMU:InvalidRealtimeConfig', 'recordingDirectory must be scalar text.');
end
end

function defaults = getDefaultsWithoutValidation()
analysis = getDrivingAnalysisConfig(); imu = getImuConfig();
defaults = struct('sampleRateHz', imu.sampleRateHz, ...
    'callbackPeriodMs', imu.callbackPeriodMs, 'pollPeriodSeconds', 0.02, ...
    'maximumPollSamples', imu.callbackBufferCapacity, ...
    'lowPassCutoffHz', analysis.lowPassCutoffHz, ...
    'medianWindowSamples', analysis.medianWindowSamples, ...
    'outlierMadThreshold', analysis.outlierMadThreshold, ...
    'brakingStartThreshold', analysis.brakingStartThreshold, ...
    'brakingStopThreshold', analysis.brakingStopThreshold, ...
    'accelerationStartThreshold', analysis.accelerationStartThreshold, ...
    'accelerationStopThreshold', analysis.accelerationStopThreshold, ...
    'lateralStartThreshold', analysis.lateralStartThreshold, ...
    'lateralStopThreshold', analysis.lateralStopThreshold, ...
    'yawRateStartThresholdDegPerSecond', analysis.yawRateStartThresholdDegPerSecond, ...
    'yawRateStopThresholdDegPerSecond', analysis.yawRateStopThresholdDegPerSecond, ...
    'verticalShockThreshold', analysis.verticalShockThreshold, ...
    'jerkCandidateThreshold', analysis.jerkCandidateThreshold, ...
    'minimumEventDurationSeconds', analysis.minimumEventDurationSeconds, ...
    'maximumEventSilenceSeconds', 0.4, 'verticalShockReleaseSamples', 5, ...
    'maximumSampleAgeMs', imu.maximumCallbackSampleAgeMs, 'historySeconds', 30, ...
    'eventHistoryLimit', 1000, 'stopOnOverflow', true, ...
    'stopOnSequenceGap', false, 'maximumConsecutiveErrors', 3, ...
    'stopDrainTimeoutSeconds', 0.5, 'stopDrainEmptyPasses', 3, ...
    'stopDrainPollIntervalSeconds', 0.005, ...
    'enableLivePlot', true, 'plotRefreshHz', 10, 'enableRecording', false, ...
    'recordingDirectory', "sessions", ...
    'maximumRecordingDurationSeconds',8*60*60, ...
    'minimumFreeDiskBytes',1024^3,'maximumSessionBytes',20*1024^3, ...
    'recordingGuardPeriodSeconds',1.0, ...
    'UseTimer', true, ...
    'DisconnectImuOnDelete', false, 'AllowSyntheticCalibration', false);
end
